name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/nowayhecodes/clint

    - name: Debug
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
      env:
        GOPATH: /home/runner/work/clint/go

    - name: Test
      run: |
        go get -u golang.org/x/tools/cmd/cover
        go test -cover $(go list ./...)
      env:
        GOPATH: /home/runner/work/clint/go

    - name: Build
      run: go build
      env:
        GOPATH: /home/runner/work/clint/go
